on: [push]

jobs:
  obs_helper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Authenticate to Huawei Cloud
        uses: huaweicloud/auth-action@v1.0.0
        with: 
          access_key_id: ${{ secrets.ACCESSKEY }} 
          secret_access_key: ${{ secrets.SECRETACCESSKEY }}
          region: 'ap-southeast-2'
        
      - name: Upload File to OBS
        uses: huaweicloud/obs-helper@v1.4.0
        id: upload_file_to_obs
        with:
          bucket_name: 'andreani-poc'
          local_file_path: ./src/
          # ./resource/upload/file1.txt
          obs_file_path: git_testNoteBookPublic/src/
          operation_type: upload
  
  
 
          
